name: CI Workflow

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-test:
    runs-on: self-hosted

    container:
      image: node:16-alpine

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Run Formatter
        run: npm run format

      - name: Run Linter
        run: npm run lint

      - name: Run Tests
        run: npm run test

      - name: Build
        run: npm run build
